services:
  backupper:
    container_name: backupper
    restart: unless-stopped
    build: .
    volumes:
      # - /opt/data/backupper:/app/data
      # - /var/log/backupper.log:/app/backupper.log

      - ./data:/app/data
      - ./backupper.log:/app/backupper.log
